// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mincssuyfzyrtuwooeyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pbmNzc3V5Znp5cnR1d29vZXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMDU0MDUsImV4cCI6MjA1Nzc4MTQwNX0.QdPht-VMUa-tSiDrTAb5KXQPe7lLe8tXswCz_xvNjBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);